---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      name: deployment-1
      labels:
        name: busybox-pod
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command:
            - sh
            - "-c"
            - echo hello Kubernetes && sleep 3600